### ISSUE TITLE
Multiple definitions of bobyqa_test

### ISSUE THREAD

**Issue by samuel-watson** [ypan1988/rminqa#1]
Hi @ypan1988 !

Hope things are going well!

When importing the headers from rminqa if the header is imported more than once there is a multiple definitions issue for the function `bobyqa_test`.  I think that's because it is declared in bobyqa.h and then defined in bobyqa_impl.h, so each time you use the headers it generates a new definition of `bobyqa_test`. To solve, if it were C++ then you'd make it inline function or wrap in a class or namespace, so it doesn't get redefined. However, it looks like it's in C so I'm not sure what the best solution is here. Do you know how to fix?

**Comment by ypan1988** [comment]
Hi @samuel-watson . I will have a check this weekend.

**Comment by ypan1988** [comment]
Let's comment out function definition of "bobyqa_test" and line 163 of the file. Have a check if that will solve the problem. If yes, I will submit it CRAN. Thanks.

**Comment by samuel-watson** [comment]
Thanks @ypan1988. I will test this out. I'm changing some of the other packages over to Eigen from Armadillo, as it seems a bit faster and is more compatible with some of the other packages, so I'll create a fork of this package to create an Eigen version and test the headers at the same time.

**Comment by ypan1988** [comment]
Hi @samuel-watson . I am thinking that it might be better to transfer the ownership of this project to you??
One thing to note is that we need to make sure the .h files under inst/include/ and src/ should be exactly the same.

**Comment by samuel-watson** [comment]
Thanks @ypan1988 - happy to take ownership if that's easier. I removed all the headers in the src/ folder since they aren't necessary as you can just include the header from the inst/include/ folder (e.g. `#include <../inst/include/rbobyqa.h>`). I just removed the dependency on armadillo altogether and used only Rcpp since no linear algebra is being done and they are quite big libraries. All the updates are in the pull request #2 . I can merge the fork, but wanted to check you were ok with it!

**Comment by ypan1988** [comment]
Hi @samuel-watson. Merged as requested, and I will now try to transfer the ownership of this repo to you. Thanks!

**Comment by ypan1988** [comment]
@samuel-watson, "samuel-watson/rminqa already exists",  I guess you need to get rid of your repo for rminqa first? Once that is done, I will try again. Thanks!
